---
- name: Set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: DROP

- name: Set the policy for the FORWARD chain to DROP
  iptables:
    chain: FORWARD
    policy: DROP

- name: Set the policy for the OUTPUT chain to DROP
  iptables:
    chain: OUTPUT
    policy: DROP